vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/
            upload_destination: '%kernel.project_dir%/public/images/'
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
 
